main is org.apache.maven.wrapper.MavenWrapperMain from maven-wrapper

[plexus.core]
load ${maven.home}/lib/maven-wrapper-*.jar
load ${maven.home}/lib/plexus-classworlds-*.jar
load ${maven.home}/lib/plexus-io-*.jar

[plexus.core]
optionally load ${maven.home}/lib/logback-*.jar
optionally load ${maven.home}/lib/slf4j-*.jar

[plexus.core]
optionally load ${maven.home}/lib/maven-shared-utils-*.jar
